services:
    app.extension.listener:
        class: AppBundle\Listener\DoctrineExtensionListener
        calls:
            - [setContainer, ["@service_container"]]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
