# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.doctrine.encode_password_listener:
        class: AppBundle\Doctrine\EncodePasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.confirmation_mail:
        class: AppBundle\Util\ConfirmationMail
        arguments: ["@mailer"]
        autowire: true

    app.compare_json:
        class: AppBundle\Util\CompareJson
        arguments: ["@security.password_encoder"]

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
 #twig.extension.text:
  #   class: Twig_Extensions_Extension_Text
   #  tags:
    #     - { name: twig.extension }





